image: maven:3.5.3-jdk-8

stages:
  - build
  - test

Compilation:
  stage: build
  script: "mvn clean compile assembly:single"
  artifacts:
    name: "Dropbox-jar"
    paths:
    - "target/*.jar"
    expire_in: 1 week

Test_1:
  stage: test
  script:
  - java -jar target/UploadFilesDpx.jar -CONFIG test/Test_1/CONFIG.txt
  artifacts:
    name: "Results-Upload"
    paths:
    - "test/Test_1/URL.txt"
    expire_in: 1 week

Test_2:
  stage: test
  script:
  - java -jar target/UploadFilesDpx.jar -CONFIG test/Test_2/CONFIG.txt
  artifacts:
    name: "Results-Upload"
    paths:
    - "test/Test_2/URL.txt"
    expire_in: 1 week

Test_3:
  stage: test
  script:
  - java -jar target/UploadFilesDpx.jar -CONFIG test/Test_3/CONFIG.txt
  artifacts:
    name: "Results-Upload"
    paths:
    - "test/Test_3/URL.txt"
    expire_in: 1 week

Test_4:
  stage: test
  script:
  - java -jar target/UploadFilesDpx.jar -CONFIG test/Test_4/CONFIG.txt
  artifacts:
    name: "Results-Upload"
    paths:
    - "test/Test_4/URL.txt"
    expire_in: 1 week
